// src/components/Showcase/showcaseConfig.js
export const showcaseConfig = [
  {
    category: 'Layout',
    components: [
      {
        name: 'Stack',
        description: 'Flexible container for spacing and layout with directional support',
        path: 'Stack',
        variants: 11,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Grid',
        description: 'CSS Grid based responsive layout system',
        path: 'Grid',
        variants: 11,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Container',
        description: 'Responsive container with max-width constraints',
        path: 'Container',
        variants: 7,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Box',
        description: 'Flexible box component with styling support',
        path: 'Box',
        variants: 1,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Paper',
        description: 'Surface elevation component with shadow support',
        path: 'Paper',
        variants: 9,
        a11y: 'WCAG 2.1 AA',
      },
    ],
  },
  {
    category: 'Inputs & Controls',
    components: [
      {
        name: 'Button',
        description: 'Primary action button with multiple variants and states',
        path: 'Button',
        variants: 6,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'ButtonGroup',
        description: 'Group of buttons with exclusive or multiple selection',
        path: 'ButtonGroup',
        variants: 9,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'ToggleButton',
        description: 'Toggle button with on/off states and groups',
        path: 'ToggleButton',
        variants: 9,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'TextInput',
        description: 'Text input field with validation and helper text',
        path: 'TextInput',
        variants: 4,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Checkbox',
        description: 'Checkbox input with label support',
        path: 'Checkbox',
        variants: 2,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Radio',
        description: 'Radio button input for single selection',
        path: 'Radio',
        variants: 2,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Select',
        description: 'Dropdown select with multiple variants',
        path: 'Select',
        variants: 6,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Switch',
        description: 'Toggle switch for boolean values',
        path: 'Switch',
        variants: 1,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Slider',
        description: 'Slider input for numeric ranges',
        path: 'Slider',
        variants: 2,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Rating',
        description: 'Star rating component',
        path: 'Rating',
        variants: 1,
        a11y: 'WCAG 2.1 AA',
      },
    ],
  },
  {
    category: 'Data Display',
    components: [
      {
        name: 'Table',
        description: 'Data table with sorting, pagination, and selection',
        path: 'Table',
        variants: 7,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'List',
        description: 'List display with multiple item variants',
        path: 'List',
        variants: 6,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Card',
        description: 'Card container for grouped content',
        path: 'Card',
        variants: 5,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'StatCard',
        description: 'Statistics display card with colors and icons',
        path: 'StatCard',
        variants: 9,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Avatar',
        description: 'User avatar component with initials',
        path: 'Avatar',
        variants: 4,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Badge',
        description: 'Badge component for counts and status',
        path: 'Badge',
        variants: 3,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Divider',
        description: 'Content divider with multiple variants',
        path: 'Divider',
        variants: 8,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Chip',
        description: 'Small interactive chip component',
        path: 'Chip',
        variants: 3,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Typography',
        description: 'Text component with 18 variants and color system',
        path: 'Typography',
        variants: 18,
        a11y: 'WCAG 2.1 AA',
      },
    ],
  },
  {
    category: 'Feedback & Status',
    components: [
      {
        name: 'Dialog',
        description: 'Modal dialog with multiple specialized variants',
        path: 'Dialog',
        variants: 11,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Toast',
        description: 'Notification toast with hooks and provider',
        path: 'Toast',
        variants: 3,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Snackbar',
        description: 'Brief notification messages',
        path: 'Snackbar',
        variants: 10,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Alert',
        description: 'Alert component with severity levels',
        path: 'Alert',
        variants: 4,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Tooltip',
        description: 'Tooltip with 12 positioning options',
        path: 'Tooltip',
        variants: 12,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Progress',
        description: 'Progress bar with multiple color options',
        path: 'Progress',
        variants: 8,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Loader',
        description: 'Loading spinner component',
        path: 'Loader',
        variants: 7,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Skeleton',
        description: 'Skeleton placeholder with animations',
        path: 'Skeleton',
        variants: 10,
        a11y: 'WCAG 2.1 AA',
      },
    ],
  },
  {
    category: 'Navigation',
    components: [
      {
        name: 'Link',
        description: 'Accessible link with hotlink styling',
        path: 'Link',
        variants: 11,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Breadcrumb',
        description: 'Navigation breadcrumb trail',
        path: 'Breadcrumb',
        variants: 4,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Pagination',
        description: 'Page navigation control',
        path: 'Pagination',
        variants: 6,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Menu',
        description: 'Dropdown menu with multiple variants',
        path: 'Menu',
        variants: 9,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'BottomNavigation',
        description: 'Bottom navigation bar',
        path: 'BottomNavigation',
        variants: 2,
        a11y: 'WCAG 2.1 AA',
      },
    ],
  },
  {
    category: 'Surfaces & Headers',
    components: [
      {
        name: 'AppBar',
        description: 'Application header with variants',
        path: 'AppBar',
        variants: 5,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Footer',
        description: 'Page footer component',
        path: 'Footer',
        variants: 5,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Header',
        description: 'Page header component',
        path: 'Header',
        variants: 5,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Sidebar',
        description: 'Sidebar navigation',
        path: 'Sidebar',
        variants: 4,
        a11y: 'WCAG 2.1 AA',
      },
    ],
  },
  {
    category: 'Process & Forms',
    components: [
      {
        name: 'Stepper',
        description: 'Step indicator for multi-step forms',
        path: 'Stepper',
        variants: 6,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Autocomplete',
        description: 'Input with autocomplete suggestions',
        path: 'Autocomplete',
        variants: 3,
        a11y: 'WCAG 2.1 AA',
      },
    ],
  },
  {
    category: 'Other',
    components: [
      {
        name: 'Colors',
        description: '80x80 color swatches from design system',
        path: 'Colors',
        variants: 1,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Icons',
        description: 'Material Design Icons integration',
        path: 'Icons',
        variants: 1,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Spacing',
        description: 'Design system spacing guide',
        path: 'Spacing',
        variants: 1,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'MainLayout',
        description: 'Main page layout wrapper',
        path: 'MainLayout',
        variants: 2,
        a11y: 'WCAG 2.1 AA',
      },
      {
        name: 'Modal',
        description: 'Modal component',
        path: 'Modal',
        variants: 6,
        a11y: 'WCAG 2.1 AA',
      },
    ],
  },
];
